name: '${COMPOSE_PROJECT_NAME:?COMPOSE_PROJECT_NAME must be set}'

services:
  seaweedfs:
    ports: !override
      - '${DEVCONTAINER_STORAGE_PORT:-8334}:8333'
      - '${DEVCONTAINER_STORAGE_ADMIN_PORT:-23647}:23646'
  workspace:
    ports:
      - '${DEVCONTAINER_WEB_PORT:-5174}:5173'
      - '${DEVCONTAINER_API_PORT:-8788}:8787'
